# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - "*"

variables:
- name: BUILD_BRANCH
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    value: $(System.PullRequest.TargetBranch)
  ${{ else }}:
    value: $(Build.SourceBranch)

stages:
- stage: Build

  jobs:
  - job:
    displayName: "amd64/ubuntu-20.04"
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - script: |
        echo $(BUILD_BRANCH)