parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64

- name: pool
  type: string
  values:
  - sonicbld
  - sonic-common
  - sonicbld-armhf
  - sonicbld-arm64
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: artifact_name
  type: string

- name: run_unit_test
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ else }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}

  steps:
  - checkout: self
    clean: true
  - script: |
      set -ex
      sudo apt-get update
      sudo apt-get install -qq -y \
        libhiredis-dev \
        libnl-3-dev \
        libnl-genl-3-dev \
        libnl-route-3-dev \
        libnl-nf-3-dev \
        swig3.0
    displayName: "Install dependencies"
  - script: |
      set -ex
      rm ../*.deb || true
      ./autogen.sh
      dpkg-buildpackage -us -uc -b -j$(nproc)
      mv ../*.deb .
    displayName: "Compile sonic swss common"
  - ${{ if eq(parameters.run_unit_test, true) }}:
    - script: |
        set -ex
        sudo pip install Pympler==0.8
        sudo apt-get install -y redis-server
        sudo sed -i 's/notify-keyspace-events ""/notify-keyspace-events AKE/' /etc/redis/redis.conf
        sudo sed -ri 's/^# unixsocket/unixsocket/' /etc/redis/redis.conf
        sudo sed -ri 's/^unixsocketperm .../unixsocketperm 777/' /etc/redis/redis.conf
        sudo sed -ri 's/redis-server.sock/redis.sock/' /etc/redis/redis.conf
        sudo service redis-server restart

        sudo dpkg -i libswsscommon_*.deb
        sudo dpkg -i python-swsscommon_*.deb

        ./tests/tests
        redis-cli FLUSHALL
        pytest
      displayName: "Run swss common unit tests"
  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss common debian packages"
