parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64

- name: pool
  type: string
  values:
  - sonicbld
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: artifact_name
  type: string

- name: run_unit_test
  type: boolean
  default: false

- name: archive_gcov
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ if eq(parameters.pool, 'default') }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest

  steps:
  - script: |
      sudo apt-get install -qq -y \
        libhiredis-dev \
        libnl-3-dev \
        libnl-genl-3-dev \
        libnl-route-3-dev \
        libnl-nf-3-dev \
        swig3.0
    displayName: "Install dependencies"
  - script: |
      set -ex
      ./autogen.sh
      fakeroot debian/rules DEB_CONFIGURE_EXTRA_FLAGS='--enable-code-coverage' CFLAGS="" CXXFLAGS="" binary && cp ../*.deb .
    displayName: "Compile sonic swss common with coverage enabled"
  - ${{ if eq(parameters.run_unit_test, true) }}:
    - script: |
        set -ex
        sudo pip install Pympler==0.8
        sudo apt-get install -y redis-server
        sudo sed -i 's/notify-keyspace-events ""/notify-keyspace-events AKE/' /etc/redis/redis.conf
        sudo sed -ri 's/^# unixsocket/unixsocket/' /etc/redis/redis.conf
        sudo sed -ri 's/^unixsocketperm .../unixsocketperm 777/' /etc/redis/redis.conf
        sudo sed -ri 's/redis-server.sock/redis.sock/' /etc/redis/redis.conf
        sudo service redis-server restart

        sudo dpkg -i libswsscommon_*.deb
        sudo dpkg -i python-swsscommon_*.deb

        sudo ./tests/tests && redis-cli FLUSHALL && pytest

        gcovr -r ./ -x -o coverage.xml
        cd common
        mkdir -p htmlcov
        gcovr -r ./ --html --html-details -o htmlcov/index.html
      displayName: "Run swss common unit tests"
  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss common debian packages"
  - ${{ if eq(parameters.archive_gcov, true) }}:
    - script: |
        set -ex
        # Install .NET CORE
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-add-repository https://packages.microsoft.com/debian/10/prod
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-5.0
      displayName: "Install .NET CORE"
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/common/htmlcov/'
      displayName: 'Publish test coverage'
  - ${{ if and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['DIFF_COVER_DISABLE'], 'true')) }}:
    - script: |
        sudo pip install diff-cover
        target_branch=$(System.PullRequest.TargetBranch)
        compare_branch=origin/${target_branch#refs/heads/}
        mkdir -p .coverage/htmlcov
        converage_files="$DIFF_COVER_COVERAGE_FILES"
        if [ -z "$converage_files" ]; then
          converage_files="$(find . -maxdepth 2 -name coverage.xml)"
        fi
        if [ -z "$converage_files" ]; then
          echo "Skipped, the coverage files not found"
          exit 0
        fi
        diff-cover $converage_files --ignore-unstaged --compare-branch=$compare_branch --html-report=.coverage/htmlcov/index.html
        diff-cover $converage_files --ignore-unstaged --compare-branch=$compare_branch --json-report=.coverage/diff-cover.json
        echo "##vso[task.setvariable variable=disable.coverage.autogenerate;]true"
        echo "##vso[task.setvariable variable=has.coverage.files;]true"
      displayName: "Show diff coverage"
      continueOnError: true
    - ${{ if ne(variables['DIFF_COVER_CHECK_DISABLE'], 'true') }}:
      - task: PythonScript@0
        inputs:
          scriptSource: inline
          script: |
            import json, requests, os, datetime
            cover = {}
            checkThreshold=os.environ.get('DIFF_COVER_CHECK_THRESHOLD')
            if not checkThreshold:
              checkThreshold = '0'
            threshold = 0
            try:
              threshold = float(checkThreshold)
            except:
              print('Failed to parse the DIFF_COVER_CHECK_THRESHOLD={0} to float'.format(checkThreshold))
              exit(0)
            with open(".coverage/diff-cover.json", "r") as f:
              cover=json.load(f)
            properties = {
              'pullRequestId': $(System.PullRequest.PullRequestNumber),
              'repoUri': '$(System.PullRequest.SourceRepositoryURI)',
              'targetBranch': '$(System.PullRequest.TargetBranch)',
              'sourceCommitId': '$(system.pullRequest.sourceCommitId)',
              'sourceVersion': '$(Build.SourceVersion)',
              'jobName': '$(Agent.JobName)',
              'jobId': '$(System.JobId)',
              'definitionName': '$(Build.DefinitionName)',
              'stageName': '$(System.StageName)',
              'jobAttempt': '$(System.JobAttempt)',
              'timestamp': datetime.datetime.now().isoformat(),
              'cover.threshold': threshold,
              'cover.num_lines': cover.get("total_num_lines"),
              'cover.num_violations': cover.get("total_num_violations"),
              'cover.percent_covered': cover.get("total_percent_covered"),
            }
            data = [
              {
                'op': 'add',
                'path': '/codediff.{0}'.format('$(Agent.JobName)'),
                'value': json.dumps(properties)
              }
            ]
            url="$(System.CollectionUri)$(System.TeamProjectId)/_apis/build/builds/$(Build.BuildId)/properties?api-version=6.0-preview.1"
            authentication='Bearer {0}'.format(os.environ.get('SYSTEM_ACCESSTOKEN'))
            headers = {"Authorization":authentication, "Content-Type":"application/json-patch+json"}
            response = requests.patch(url, headers=headers, data=json.dumps(data))
            if (response.status_code == 200):
              print('The request was succeeded.')
            else:
              print('The request was failed, with error: {0}'.format(response.status_code))
              print('The failure reason is {0}'.format(response.reason))
        displayName: 'Update Build coverage'
        condition: eq(variables['has.coverage.files'], 'true')
        continueOnError: true
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    - ${{ if ne(variables['DIFF_COVER_COVERAGE_REPORT_DISABLE'], 'true') }}:
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/diff-cover/htmlcov'
        displayName: 'Publish coverage'
        condition: eq(variables['has.coverage.files'], 'true')
        continueOnError: true
